config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :workouts
    resources :measurements
  end
  get "/" => "sessions#new"
  post "/" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  root "sessions#new"
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
  has_many :progresses
  has_many :users, through: :progress
end

app/models/progress.rb
class Progress < ActiveRecord::Base
  belongs_to :user
  belongs_to :measurement
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :workouts

  has_many :progresses
  has_many :measurements, through: :progresses

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }

  has_attached_file :avatar, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :user
  validates :name, :reps, :sets, :weight, :user_id, :phase, :rest, :day, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/' unless current_user
  end

  def require_admin
    redirect_to '/' unless current_user.admin?
  end
  
end

app/controllers/concerns/measurement_controller.rb
class SessionsController < ApplicationController
end

app/controllers/daily_workouts_controller.rb
class DailyWorkoutsController < ApplicationController

  def index
  end

  def new
  end

  def create
    # binding.pry
  end

  def update
  end

  def destroy
  end
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
  end

  def create
    if @user = User.find_by(email: user_params[:email])
      if @user.authenticate(user_params[:password])
        session[:user_id] = @user.id
        if @user.admin?
          redirect_to users_path
        else
          redirect_to(@user)
        end
      else
        flash[:error] = "Please login again!"
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :require_user, only: [:show]
  before_action :require_admin, only: [:index, :edit, :destroy]

  def index
    @users = User.where(admin: false)
  end

  def show
    @user = User.find_by(id: params[:id])
    @phases = phases(@user) if @user
    @phases.sort!
    if @user.nil?
       if current_user.admin?
        flash[:error] = "User doesn't exist!"
        redirect_to users_path
      else
        flash[:error] = "You don't have access!"
        redirect_to user_path(session[:user_id])
      end

    elsif current_user.admin?
      @admin = current_user
      if @user.workouts && @user
       @workouts = @user.workouts
       render 'users/show', :locals => {:phases => @phases, workouts: @workouts }
      end
    else
      #################### Prevents clients to see other client's data###################
      unless session[:user_id] == @user.id
        flash[:error] = "You don't have access!"
        redirect_to user_path(session[:user_id])
      return
      end
      @workouts = current_user.workouts
      render 'users/show', :locals => {phases: @phases, workouts: @workouts }
    end
  end


  def new
  end

  def create
    if @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to @user
      else
        redirect_to new_user_path
      end
    else
      redirect_to new_user_path
    end
  end

  def edit
      @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(email: params[:user][:email])

    if @user.update_attributes(user_params)
      flash[:success] = "User successfully updated!"
      redirect_to users_path
    else
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    client = User.find_by(id: params[:id])
    if current_user.admin?
      if client.destroy
        flash[:success] = "User successfully deleted!"
        redirect_to users_path
      else
        redirect_to users_path
      end
    else
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end

  def phases(user)
    phase_collection = []
    user.workouts.each do |workout|
      phase_collection.push(workout.phase)
      phase_collection = phase_collection.uniq
    end
    return phase_collection
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  def index
    current_user
    @workout = Workout.find_by(id: params[:id])
  end

  def show
    current_user
    @workout = Workout.find_by(id: params[:id])
  end

  def new
    @workout = Workout.new
    @user = User.find_by(id: params[:user_id])
    @workout.user_id = @user.id
  end

  def create
    @workout = Workout.new(workout_params)
    @workout.user_id = params[:user_id]
    if @workout.save
      flash[:success] = "Workout successfully created"
      redirect_to user_path(params[:user_id])
    else
      flash[:error] = "Workout was not created"
      redirect_to user_path(params[:user_id])
    end
  end

  def edit
    if current_user.admin?
      @workout = Workout.find_by(id: params[:id])
      @user = User.find_by(id: params[:user_id])
    else
      redirect_to logout_path
    end
  end

  def update
    if request.xhr?
      @workout = Workout.find_by(id: params[:id])
      @workout.update(completed: true)
      render :json=>true
    else
      @workout = Workout.find_by(id: params[:id])
      @user = User.find_by(id: params[:user_id])
      if @workout.update(workout_params)
        flash[:success] = "Workout successfully updated!"
        redirect_to user_path(@user)
      else
        flash[:error] = "Your missing a field."
        redirect_to edit_user_workout_path(@user, @workout)
      end
    end
  end

  def destroy
    @workout = Workout.find_by(id: params[:id])
    if @workout.destroy
      flash[:success] = "Workout successfully deleted!"
      redirect_to user_path
    end
  end

  private

  def workout_params
    params.require(:workout).permit(:name, :sets, :reps, :weight, :completed, :rest, :phase, :day, :note, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/views/layouts/_nav_bar.html.erb
<% if current_user.admin? %>
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="navbar-brand glyphicon glyphicon-check"></span>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/users">Home</a></li>
            <!-- If user logged in and there is a session id then show below -->
            <% if current_user %>


              <li><%= link_to "logout", {:controller=> "sessions", :action=> "destroy"}, method: :delete %></li>

              <li><a href="/users/<%= session[:user_id] %>"><span class="glyphicon glyphicon-user"></span>  <%= current_user.name %></a></li>

            <% end %>

          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkOutTracker</title>

  <meta http-equiv="X-UA-Compatible" content=="IE=edge"/>
  <meta name=viewport content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <!-- D3 CDN -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.16/d3.min.js"></script>

  <!-- chartkick js -->
  <script src="https://www.google.com/jsapi"></script>
  <script src="chartkick.js"></script>
</head>




<% if !current_user %>
<body class="splash">
<% else %>
<body>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/_admin_nav.html.erb
<div class="cover">
</div>

<div class="profile-container">
  <img class="avatar" src="http://fitnesssf.com/wp-content/uploads/2014/09/fsf_web.trainers_soma_eddyAguirre111714.jpg" height="500px" width="500px">
  <br>
  <strong><%= current_user.name %></strong>
</div>

<br>
<br>

<ul class="list-group">
  <center>
    <!-- Single button -->
    <div class="btn-group">
      <a href="/users" class="btn btn-default">Clients</a>
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="glyphicon glyphicon-user"></span>  <%= current_user.name %> <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to "logout", {:controller=> "sessions", :action=> "destroy"}, method: :delete %></li>
      </ul>
    </div>
  </center>
</ul>

app/views/users/_admin_view_client_workouts.html.erb
     <!--    Show phase one by one if there is phase -->
      <% if @phases && @phases.length > 0 %>
        <% @phases.each do |phase_num| %>
          <table class="table table-striped">
            <tr>
              <th><a href="#"><h3>Phase <%= phase_num %><h3></a></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
            <% workout_for_phase = @workouts.where(phase: phase_num) %>

            <!-- Show days one by one in each phase -->
            <% days = [] %>
            <% workout_for_phase.each do |workout| %>
              <% if workout.day %>
                <% days.push(workout.day) %>
              <% end %>
            <% end %>
            <% days = days.uniq %>
            <% days.sort! %>
            <% days.each do |day| %>
              <tr>
                <th><a href="#">Day <%= day %></a></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
              </tr>
              <tr>
                <th>Name</th>
                <th>Completed</th>
                <th>Reps</th>
                <th>Sets</th>
                <th>Weight</th>
                <th>Note</th>
              </tr>
              <% per_day_workouts = workout_for_phase.where(day: day) %>
              <% per_day_workouts.each do |workout| %>
                <tr>
                  <td><%= workout.name %><%= "   " %><%= link_to "Edit", edit_user_workout_path(@user, workout) %> | <%= link_to 'Delete', user_workout_path(@user, workout), method: :delete,
                                     data: { confirm: 'Are you sure?'} %></td>
                  <td><%= workout.completed ? "Yes" : "No" %></td>
                  <td><%= workout.reps %></td>
                  <td><%= workout.sets %></td>
                  <td><%= workout.weight %></td>
                  <td><%= workout.note %></td>
                </tr>
              <% end %>
            <% end %>
          </table>
        <% end %>    <!-- End of day view -->
      <% end %>  <!-- End of phase view -->


      <%= link_to 'Back', users_path %>
    </div>

app/views/users/_client_show_heading.html.erb
    <div class="cover">
    </div>

     <div class="profile-container">
    <!-- Avatar image -->
    <%= image_tag @user.avatar.url(:thumb), class: "avatar" %>

    <br>

    <strong><%= current_user.name %></strong>
    </div> 

    <div align="center">Congratulations <strong><%= @user.name.capitalize %></strong> For Making It This Far!<br>
    Here is Your Progress:
    </div>    
    <br><br>

    <ul class="list-group">
      <center>
        <!-- Single button -->
        <div class="btn-group">
          <button id="show-goals" type="button" class="btn btn-default">Workouts</button>
          <button type="button" class="btn btn-default">Progress</button>
          <button id="show-measurements" type="button" class="btn btn-default">Measurements</button>
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-user"></span>  <%= current_user.name %> <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to "logout", {:controller=> "sessions", :action=> "destroy"}, method: :delete %></li>
          </ul>
        </div>
      </center>
    </ul>
    

app/views/users/_client_workouts.html.erb
<div id="glist">
      <% @phases.each do |phase_num| %>

        <h1>Phase  <%= phase_num %></h1>
        <% phase_workout = @workouts.select {|workout| workout.phase == phase_num} %>

        <% days = [] %>
        <% phase_workout.each do |workout| %>
          <% days.push(workout.day) %>
        <% end %>
        <% days = days.uniq %>
        <% days.sort! %>
        <% days.each do |day| %>
          <h2> Day <%= day %></h2>
          <% day_workout = phase_workout.select {|workout| workout.day == day} %>
          <% day_workout.each do |workout| %>
            <% if workout.completed == false %>
              <li class="list-group-item list-group-item-success">
                <strong><%= workout.name %></strong>
                <input type="submit" value="Complete" class="btn-xs btn-success pull-right wobtn" name="<%= workout.user_id %>" id="<%= workout.id %>">
              </li>
            <% else %>
              <li class="list-group-item list-group-item-success">
                <strong><%= workout.name %></strong>
              </li>
            <% end %>
            <li class="list-group-item">
              <span class="badge"><%= workout.reps %></span>Reps:
            </li>
            <li class="list-group-item">
              <span class="badge"><%= workout.sets %></span>Sets:
            </li>
            <li class="list-group-item">
              <span class="badge"><%= workout.weight %></span>Weight:
            </li>
          <% end %>
        <% end %>
      <% end %>
    </div>

app/views/users/_daily_workout_data.html.erb
<% @workouts.each do |workout| %>
  <% if workout.phase == 1 && workout.day == 1 %>
      <tr>
        <td><%= workout.updated_at.strftime("%b. %d %Y") %></td>
        <td><%= workout.updated_at.strftime("%H:%M") %></td>
        <td><%= workout.name %></td>
        <td><%= workout.reps %></td>
        <td><%= workout.sets %></td>
        <td><%= workout.weight %></td>
        <td><%= workout.completed ? "Yes" : "No" %></td>
      </tr>
  <% end %>
<% end %>

app/views/users/_flash_message.html.erb
<!-- Flash message when successfully updating/destroying a user -->
<% if flash[:success] %>
  <div class="alert alert-success"><%= flash[:success] %></div>
<% elsif flash[:error] %>
  <div class="alert alert-danger"><%= flash[:error] %></div>
<% end %>
<!-- End of flash message -->

app/views/users/_form.html.erb
<%= form_for @user, html: { multipart: true } do |f| %>

  <%= f.label :avatar %>
  <%= f.file_field :avatar %>
  <br>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit "Save changes" %>
  <br>
  <%= link_to 'Back', users_path %>
<% end %>

app/views/users/_graphs.html.erb
<!-- D3 graph for progress -->
  <!-- Graph out weight -->
  <hr>
  <div class="container">
  <h1 class="center">Weight</h1>
  <svg id="vis_weight" class="svg_charts"></svg>

  <script type="text/javascript">graphOutWeight();</script>

  <!-- Graph out body fat -->
  <hr>
  <h1 class="center">Body Fat</h1>
  <svg id="vis_body_fat" class="svg_charts"></svg>
  <script type="text/javascript">graphOutBodyFat();</script>
  </div>

app/views/users/_measurements.html.erb
    <div id="mlist">
      <table id="measurement" class="table table-striped">
        <tr>
          <th>Measurements</th>
          <th></th>
        </tr>
        <tr>
          <th>Item</th>
          <th>Status</th>
        </tr>

        <tr> <!-- Add measurement to iterate last measurements -->
          <td>Weight:</td>
          <td>50 LB</td>
        </tr>
        <tr>
          <td>Body Fat:</td>
          <td>12 %</td>
        </tr>
        <tr>
          <td>Dead Lift:</td>
          <td>12 LB</td>
        </tr>
        <tr>
          <td>Bench Press:</td>
          <td>12 LB</td>
        </tr>
        <tr>
          <td>Squat:</td>
          <td>12 LB</td>
        </tr>
        <tr>
          <td>Lat Pull Down:</td>
          <td>12 LB</td>
        </tr>
      </table>
    </div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<% if current_user && current_user.admin? %>

  <!-- Flash message when successfully updating/destroying a user -->
  <%= render 'flash_message' %>
  <!-- End of flash message -->
<%= render 'admin_nav' %>
<h1>All clients</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to "#{user.name.capitalize}", user %></td>
    <td><%= user.email %></td>
    <td><%= link_to edit_user_path(user) do %>
          <i class="glyphicon glyphicon-pencil"></i>
        <% end %>
    </td>
    <td><%= link_to user, method: :delete,
                          data: { confirm: 'Are you sure?'} do %>
          <i class="glyphicon glyphicon-remove"></i>
        <% end %>                    
    </td>
  </tr>
<% end %>
</table>

<% end %>

app/views/users/new.html.erb
<br>
<form class="form-horizontal" action='/users' method="POST" enctype="multipart/form-data">

  <label for="file">Filename:</label>
    <input type="file" name="file" id="file" />

    
  <fieldset class='col-sm-10 col-sm-offset-1'>
    <div id="legend">
      <legend class="">Register</legend>
    </div>
    <div class="control-group">
      <!-- Username -->
      <label class="control-label" for="username">First & Last Name</label>
      <div class="controls">
        <input type="text" id="username" name="user[name]" placeholder="" class="input-xlarge">
        <p class="help-block">Username can contain any letters or numbers, without spaces
        </p>
      </div>
    </div>
    <div class="control-group">
      <!-- E-mail -->
      <label class="control-label" for="email">E-mail</label> <div class="controls">
      <input type="text" id="email" name="user[email]" placeholder="" class="input-xlarge">
      <p class="help-block">Please provide your E-mail</p>
    </div>
  </div>
  <div class="control-group">
    <!-- Password-->
    <label class="control-label" for="password">Password</label>
    <div class="controls">
      <input type="password" id="password" name="user[password]" placeholder="" class="input-xlarge">
      <p class="help-block">Password should be at least 6 characters</p>
    </div>
  </div>
  <div class="control-group">
    <!-- Password -->
    <label class="control-label" for="password_confirm">Password (Confirm)</label>
    <div class="controls">
      <input type="password" id="password_confirm" name="user[password_confirmation]" placeholder="" class="input-xlarge">
      <p class="help-block">Please confirm password</p>
    </div>
  </div>
  <div class="control-group"> <!-- Button -->
    <div class="controls">
      <button class="btn btn-default" >Register</button>
    </div>
  </div>
  </fieldset>
</form>

app/views/users/show.html.erb
<!-- Flash message when successfully creating/updating/destroying a workout or prevent client to view other users show page -->
<%= render 'flash_message' %>

<% if current_user && current_user.admin? %>
    <%= render 'admin_nav' %>

    <div class="container">


      <!-- Title of client -->
      <h1><%= @user.name.capitalize %>'s Progress</h1>
      <h3>(<%= @user.email %>)</h3>
      <!-- End of title of client -->

      <!-- Button for workout -->
      <a href="/users/<%= @user.id %>/workouts/new"><button class="btn btn-lg btn-primary">Create New Workout</button></a>
      <br>
      <br>

      <%= render 'admin_view_client_workouts', :locals => {:phases => phases, workouts: @workouts } %>

    <!-- End of admin view -->


<% elsif current_user && current_user.admin != true %>
    <!-- Start of user's view -->
    <%= render 'client_show_heading' %>

    <%= render 'measurements' %>

    <%= render 'client_workouts', :locals => {:phases => phases, workouts: @workouts } %>

    <!-- D3 graph for progress -->
    <%= render 'graphs' %>

  <% end %>

app/views/workouts/_form.html.erb
<div class="container">
  <div class="page-header">
    <h1><small>Add a workout for</small> <%= @user.name.capitalize %></h1>
  </div>



  <%= form_for [@user, @workout] do |f| %>

    <%= f.label :phase %>
    <%= f.select(:phase, options_for_select([
      [1,1],
      [2,2],
      [3,3],
      [4,4],
      [5,5],
      [6,6],
      [7,7],
      [8,8],
      [9,9],
      [10,10],
      [11,11],
      [12,12],
      [13,13],
      ])) %>


    <%= f.label :day %>
    <%= f.select(:day, options_for_select([
      [1,1],
      [2,2],
      [3,3],
      [4,4]])) %>

    <br>
    <br>
    <p>Workout:
    <%= f.text_field :name, placeholder: "Name" %>

    <%= f.text_field :reps, required: true, placeholder: "Reps" %>

    <%= f.text_field :sets, required: true, placeholder: "Sets" %>

    <%= f.text_field :weight, required: true, placeholder: "Weight" %>
    </p>

    <br>
    <p> Optional:
    <%= f.label :rest %>
    <%= f.text_field :rest, value: 0, required: true %>


    <%= f.label :note %>
    <%= f.text_field :note, placeholder: "Optional" %>
    </p>
    <br>
    <%= f.submit "Submit" %>
  <% end %>

app/views/workouts/edit.html.erb
<head>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">
</head>

      <!-- Create flash when successfully in creating workout -->
      <% if flash[:success] %>
      <div class="alert alert-success"><%= flash[:success] %></div>
      <% elsif flash[:error] %>
      <div class="alert alert-error"><%= flash[:error] %></div>
      <% end %>
      <!-- End of flash message -->

<h1>Edit a workout for <%= @user.name.capitalize %></h1>

<%= render 'form' %>

<script>
  $(function() {
    var availableWorkouts = [
      '1-arm row(scap/core stability)',
      '1-arm row(scap/core stability)',
      '85% run(endurance)',
      '90% run(endurance)',
      '95% run(endurance)',
      'abs sequence 1',
      'ankle mobility(complex 1)',
      'back squat(ankle/hip mobility)',
      'ball slams',
      'bent over row(scap/core stability)',
      'bulgarian split squat(hip mobility)',
      'burpees(muscular endurance)',
      'calve raises',
      'db front squat(ankle/hip mobility)',
      'db shoulder press(scap stability)',
      'db snatch',
      'deadlift(posterior chain)',
      'double unders(endurance)',
      'db thruster(compound)',
      'farmers carry',
      'farmers hold',
      'farmer walks(heavy)',
      'frog jumps',
      'goblet squats',
      'hollow rocks',
      'inverted row(scap stability)',
      'jump squats',
      'kb swing(hip mobility)',
      'mtn climbers',
      'plank(core stability)',
      'push press(gh mobility)',
      'push-ups',
      'push-ups(stability/endurance)',
      'renegade rows(core stability)',
      'run',
      'run(endurance)',
      'squats',
      'shoulder press(shoulder stability)',
      'sit-ups',
      'squat(ankle/hip mobility)',
      'standing face-pulls',
      'superman(posterior chain)',
      'thursters',
      'trx figure 4',
      'trx forward lunge',
      'trx lateral lunges',
      'trx pidgeon stretch',
      'tuck jumps',
      'wall balls(compound)',
    ];
    $( "#workout_name" ).autocomplete({
      source: availableWorkouts
    });
  });
  </script>